---
version: '3'

services:

  {% for app_name in apps %}
    {% include 'apps/%s/composition.yaml' % app_name %}
  {% endfor %}

  musterroll:
    hostname: "musterroll"
    image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-musterroll"
    volumes:
      - "/opt/cloudfleet/data/shared/users:/opt/cloudfleet/data"
      - "/opt/cloudfleet/data/shared/tls:/opt/cloudfleet/tls"
    environment:
      CLOUDFLEET_DOMAIN: "{{'myblimp.net' | env('CLOUDFLEET_DOMAIN')}}"
    networks:
      - blimp

  escapepod:
    hostname: escapepod
    image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-escapepod:{{'latest' | env('CLOUDFLEET_STAGE')}}"
    networks:
      - blimp

  traefik:
    hostname: traefik
    image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-traefik:{{'latest' | env('CLOUDFLEET_STAGE')}}"
    volumes:
      - "/opt/cloudfleet/data/shared/tls:/opt/cloudfleet/conf/tls"
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - blimp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/cloudfleet/data/shared/tls:/acme.json

  pagekite:
    hostname: pagekite
    image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-pagekite:{{'latest' | env('CLOUDFLEET_STAGE')}}"
    environment:
      SUBDOMAINS: "cockpit;musterroll;{{';'.join(apps)}}"
      CLOUDFLEET_DOMAIN: "{{'myblimp.net' | env('CLOUDFLEET_DOMAIN')}}"
      CLOUDFLEET_SPIRE_HOST: "{{'spire.cloudfleet.io' | env('CLOUDFLEET_SPIRE_HOST')}}"
      CLOUDFLEET_SECRET: "{{'secret' | env('CLOUDFLEET_SECRET')}}"
    networks:
      - blimp
      - pagekite

networks:
  pagekite:
  blimp:
  mastodon:
    internal: true
