---
{% for app_name, app_properties in apps.iteritems() %}
{{app_name}}:
    hostname: "{{app_name}}"
    image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/{{app_properties.image}}:{{'latest' | env('CLOUDFLEET_STAGE')}}"
    volumes:
      - "/opt/cloudfleet/data/apps/{{app_name}}:/opt/cloudfleet/data"
    environment:
      CLOUDFLEET_DOMAIN: "{{'myblimp.net' | env('CLOUDFLEET_DOMAIN')}}"
{% endfor %}

escapepod:
  hostname: escapepod
  image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-escapepod:{{'latest' | env('CLOUDFLEET_STAGE')}}"

traefik:
  hostname: traefik
  image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-traefik:{{'latest' | env('CLOUDFLEET_STAGE')}}"
  volumes:
    - "/opt/cloudfleet/data/shared/tls:/opt/cloudfleet/conf/tls"

pagekite:
  hostname: pagekite
  image: "{{'registry.marina.io' | env('CLOUDFLEET_REGISTRY')}}/cloudfleet/blimp-pagekite:{{'latest' | env('CLOUDFLEET_STAGE')}}"
  environment:
    CLOUDFLEET_DOMAIN: "{{'myblimp.net' | env('CLOUDFLEET_DOMAIN')}}"
    CLOUDFLEET_HOST: "{{'blimpyard.cloudfleet.io' | env('CLOUDFLEET_HOST')}}"
    CLOUDFLEET_SECRET: "{{'secret' | env('CLOUDFLEET_SECRET')}}"
